DROP TABLE IF EXISTS JSON_DATA;

CREATE TABLE IF NOT EXISTS JSON_DATA(
    DOM VARCHAR(255),
    ID VARCHAR(255),
    MODEL VARCHAR(255),
    DATA MEDIUMTEXT);

CREATE INDEX IF NOT EXISTS JSON_DATA_INDEX ON JSON_DATA (DOM, ID, MODEL);