CREATE TABLE DOCUMENT (
    ID INT8 PRIMARY KEY,

    URL TEXT,

    STATE INT,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    LANGUAGE TEXT NOT NULL,

    WORDS_TOTAL INTEGER NOT NULL,
    FORMAT TEXT NOT NULL,
    FEATURES INTEGER NOT NULL,

    DATA_HASH INTEGER NOT NULL,
    QUALITY REAL NOT NULL,
    PUB_YEAR INTEGER NOT NULL
);