CREATE TABLE DOMAIN_COMPLAINT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DOMAIN_ID INT NOT NULL,

    CATEGORY VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    SAMPLE VARCHAR(255),
    FILE_DATE TIMESTAMP NOT NULL DEFAULT NOW(),

    REVIEWED BOOLEAN AS (REVIEW_DATE > 0) VIRTUAL,
    DECISION VARCHAR(255),
    REVIEW_DATE TIMESTAMP,

    FOREIGN KEY (DOMAIN_ID) REFERENCES EC_DOMAIN(ID) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;