
CREATE TABLE SEARCH_NEWS_FEED (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    LINK VARCHAR(255) UNIQUE NOT NULL,
    SOURCE VARCHAR(255),
    LIST_DATE DATE  NOT NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
