package nu.marginalia.converting.processor.logic;

import nu.marginalia.converting.model.DocumentHeaders;
import nu.marginalia.converting.model.DocumentTags;
import nu.marginalia.model.EdgeUrl;
import org.jsoup.Jsoup;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class DocumentGeneratorExtractorTest {

    private final DocumentGeneratorExtractor extractor = new DocumentGeneratorExtractor();

    private DocumentGeneratorExtractor.DocumentGenerator detect(String html) throws Exception {
        return detect(html, "");
    }

    private DocumentGeneratorExtractor.DocumentGenerator detect(String html, String headers) throws Exception {
        var doc = Jsoup.parse(html);
        return extractor.detectGenerator(
                new EdgeUrl("https://www.example.com/"),
                doc,
                new DocumentHeaders(headers),
                new DocumentTags(doc));
    }

    @Test
    void detectsMetaGeneratorTag() throws Exception {
        var gen = detect("<html><head><meta name=\"generator\" content=\"WordPress 6.1\"></head><body></body></html>");
        Assertions.assertTrue(gen.keywords().contains("wordpress"));
        Assertions.assertTrue(gen.keywords().contains("wordpress_6"));
    }

    @Test
    void detectsPlatformByElementId() throws Exception {
        var gen = detect("<html><body><div id=\"flarum-json-payload\">{}</div></body></html>");
        Assertions.assertTrue(gen.keywords().contains("flarum"));
    }

    @Test
    void detectsPlatformByClassName() throws Exception {
        var gen = detect("<html><body class=\"ipsApp\"></body></html>");
        Assertions.assertTrue(gen.keywords().contains("invision"));
    }

    @Test
    void detectsGeneratorByHeadComment() throws Exception {
        var gen = detect("<html><head><!-- Generated by javadoc (17) --></head><body></body></html>");
        Assertions.assertTrue(gen.keywords().contains("javadoc"));
    }

    @Test
    void detectsSneakyWordpressByScriptSrc() throws Exception {
        var gen = detect("<html><head><script src=\"/wp-content/themes/foo/script.js\"></script></head><body></body></html>");
        Assertions.assertTrue(gen.keywords().contains("wordpress"));
    }

    @Test
    void fallsBackToServerHeaders() throws Exception {
        var gen = detect("<html><body></body></html>", "Server: nginx/1.20.1");
        Assertions.assertTrue(gen.keywords().contains("nginx"));
    }
}
