CREATE TABLE IF NOT EXISTS EC_API_KEY (
    LICENSE_KEY VARCHAR(255) UNIQUE,
    LICENSE VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    RATE INT DEFAULT 10
);