CREATE TABLE IF NOT EXISTS SEARCH_FILTER
(
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_ID` VARCHAR(255) NOT NULL,
    `NAME` VARCHAR(255) NOT NULL,
    `LAST_ACCESSED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `SPEC` TEXT NOT NULL,
    CONSTRAINT CONS UNIQUE (`USER_ID`, `NAME`)
)
CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;