CREATE TABLE IF NOT EXISTS WIDE_DOMAIN_ROOTS (
    DOMAIN_TOP VARCHAR(255) NOT NULL PRIMARY KEY,
    TS_ADDED   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
