
CREATE TABLE IF NOT EXISTS EC_RANDOM_DOMAIN_SUGGESTIONS (
    DOMAIN_ID INT PRIMARY KEY,
    SUGGESTED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_RANDOM_DOMAIN_SUGGESTIONS_AT
    ON EC_RANDOM_DOMAIN_SUGGESTIONS(SUGGESTED_AT);
