-- Table holding domains that are to be migrated to a dedicated index node, along with
-- the crawl data that already exists for them.

CREATE TABLE IF NOT EXISTS DOMAIN_MIGRATION_QUEUE(
    DOMAIN_ID  INT NOT NULL PRIMARY KEY,
    DEST_NODE  INT NOT NULL,
    STATE      ENUM('NEW','MIGRATED','FAILED') NOT NULL DEFAULT 'NEW',
    TS_CHANGE  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_DOMAIN_MIGRATION_QUEUE_DOMAIN
        FOREIGN KEY (DOMAIN_ID) REFERENCES EC_DOMAIN(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS DOMAIN_MIGRATION_QUEUE__DEST_STATE
    ON DOMAIN_MIGRATION_QUEUE (DEST_NODE, STATE);
