ALTER TABLE FILE_STORAGE_BASE DROP COLUMN PERMIT_TEMP;
ALTER TABLE FILE_STORAGE_BASE ADD COLUMN TYPE_NEW VARCHAR(255) NOT NULL;

UPDATE FILE_STORAGE_BASE SET TYPE_NEW = 'CURRENT' WHERE TYPE='SSD_INDEX';
UPDATE FILE_STORAGE_BASE SET TYPE_NEW = 'WORK'    WHERE TYPE='SSD_WORK';
UPDATE FILE_STORAGE_BASE SET TYPE_NEW = 'STORAGE' WHERE TYPE='SLOW';
UPDATE FILE_STORAGE_BASE SET TYPE_NEW = 'BACKUP'  WHERE TYPE='BACKUP';

ALTER TABLE FILE_STORAGE_BASE DROP COLUMN TYPE;
ALTER TABLE FILE_STORAGE_BASE CHANGE COLUMN TYPE_NEW TYPE VARCHAR(255) NOT NULL;
