CREATE TABLE NODE_CONFIGURATION (
    ID INT PRIMARY KEY,
    DESCRIPTION VARCHAR(255),
    ACCEPT_QUERIES BOOLEAN,
    AUTO_CLEAN BOOLEAN DEFAULT TRUE,
    PRECESSION BOOLEAN DEFAULT TRUE,
    DISABLED BOOLEAN DEFAULT FALSE
);