CREATE TABLE IF NOT EXISTS DATA_DOMAIN_SCREENSHOT (
  DOMAIN_NAME VARCHAR(255) PRIMARY KEY,
  CONTENT_TYPE ENUM ('image/png', 'image/webp', 'image/svg+xml') NOT NULL,
  DATA LONGBLOB NOT NULL
)
ROW_FORMAT=DYNAMIC
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE TABLE DATA_DOMAIN_HISTORY (
    DOMAIN_NAME VARCHAR(255) PRIMARY KEY,
    SCREENSHOT_DATE DATE DEFAULT NOW()
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
